# Generated by Django 5.0.7 on 2024-07-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500, null=True)),
                ('category', models.CharField(choices=[('daytime', 'Daytime'), ('nightlife', 'Nightlife')], max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('operations_hours', models.TextField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, choices=[('$-$$', 'Low to Medium'), ('$$-$$$', 'Medium to High'), ('$$$-$$$$', 'High End')], max_length=10)),
                ('description', models.TextField(blank=True, default='no description')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='XploreATL.location')),
            ],
        ),
        migrations.CreateModel(
            name='Eatery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500, null=True)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('bakery', 'Bakery')], max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('cuisine', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('operations_hours', models.TextField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, choices=[('$-$$', 'Low to Medium'), ('$$-$$$', 'Medium to High'), ('$$$-$$$$', 'High End')], max_length=10)),
                ('description', models.TextField(blank=True, default='no description')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eateries', to='XploreATL.location')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_eateries', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='XploreATL.eatery')),
                ('bookmarked_hotspots', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='XploreATL.hotspot')),
                ('customuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='XploreATL.customuser')),
                ('favorite_eateries', models.ManyToManyField(blank=True, related_name='favorited_by', to='XploreATL.eatery')),
                ('favorite_hotspots', models.ManyToManyField(blank=True, related_name='favorited_by', to='XploreATL.hotspot')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('eatery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='XploreATL.eatery')),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='XploreATL.hotspot')),
            ],
        ),
    ]
