# Generated by Django 5.0.7 on 2024-07-25 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XploreATL', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_eateries', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='XploreATL.eatery')),
                ('bookmarked_hotspots', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='XploreATL.hotspot')),
                ('favorite_eateries', models.ManyToManyField(blank=True, related_name='favorited_by', to='XploreATL.eatery')),
                ('favorite_hotspots', models.ManyToManyField(blank=True, related_name='favorited_by', to='XploreATL.hotspot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='XploreATL.user')),
            ],
        ),
    ]
